[EXPERIMENT_PATH]
# 1600×1200の画像の入ったディレクトリ(README.mdのデータセットのフォルダ構成を参照)
img_path = ./Data/master_exp_data
# 結果を保存するディレクトリ
default_path = ./result/26_05_01

[EXPERIMENT_PARAM]
# 実験対象(membrane or nuclear or both)
experiment_subject = membrane
# 使用するネットワーク(U-Net or U-Net++)
use_network = U-Net
# Deep Supervisionを使用するか(True or False, U-Net++のみ)
deep_supervision = True
# 画像の色空間(RGB or HSV)
color = RGB
# ブレンドモード(concatenate or alpha)
blend = concatenate
# グラデーションを使用するか(True or False, membrane or bothの場合のみ)
gradation = True
higher_ratio = 0
# 損失関数(DiceLoss or BCELoss)
use_loss = DiceLoss
# 学習を開始するエポック数
start_num = 0
# エポック数
num_epochs = 20
# 学習率
lr = 5e-05
# バッチサイズ
batch_size = 32
# 1=明視野/暗視野/位相差を1系統ずつ試す(3パターン), 3=bf/df/phの使用有無をビット列で切替(7パターン). use_rgb_balance 利用時は 1 か 3
use_list_length = 3
# データ拡張の回数
data_augmentation_num = 500
# 学習画像のサイズ
train_size = (256, 256)
# 彩度の変化の範囲
saturation_mag = (0.7, 1.3)
# 明度の変化の範囲
value_mag = (0.7, 1.3)
# コントラストの変化の範囲
contrast_mag = (0.7, 1.3)
# 学習時の膨張の半径(membrane or bothの場合のみ)
radius_train = 3
# 使用するデバイス(CUDAのナンバーのリスト)
use_device = [0,1]
# 自動混合精度を使用するか(True or False)
use_autocast = True
# 自動混合精度のデータ型(bfloat16 or float16)
autocast_dtype = bfloat16
# 画像の圧縮率(1で圧縮なし, 同一画素値の圧縮幅)
compress_rate = 1
# エラーを無視するか(True or False)
ignore_error = False
# RGBバランスチャンネル追加(入力2倍)を使用するか(True or False)
use_rgb_balance = False
# RGBチャンネル色差追加(入力2倍)を使用するか(True or False)
use_rgb_chromatic = True

[EVALIATION_PARAM]
# 評価時の膨張の半径(membrane or bothの場合のみ)
radius_eval = 3
# 細胞膜の評価を開始するEpoch(membrane or bothの場合のみ)
membrane_sparse_epoch_start = 1
# 細胞膜の評価を行うEpochのステップ(membrane or bothの場合のみ)
membrane_sparse_epoch_step = 5
# 細胞膜の評価の二値化閾値の最小値(membrane or bothの場合のみ)
membrane_sparse_threshold_min = 127
# 細胞膜の評価の二値化閾値の最大値(membrane or bothの場合のみ)
membrane_sparse_threshold_max = 255
# 細胞膜の評価の閾値のステップ(membrane or bothの場合のみ)
membrane_sparse_threshold_step = 5
# 細胞膜の評価の小領域削除面積の最小値(membrane or bothの場合のみ)
membrane_sparse_del_area_min = 0
# 細胞膜の評価の小領域削除面積の最大値(membrane or bothの場合のみ)
membrane_sparse_del_area_max = 100
# 細胞膜の評価の小領域削除面積のステップ(membrane or bothの場合のみ)
membrane_sparse_del_area_step = 5
